"use strict";
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),assert=require('node:assert/strict');
const p=require('../shared/patch-package.cjs'),{makeAsar,baseFiles}=require('../tests/fixtures/asar.cjs');
// Hosted Windows TEMP may use an 8.3 alias. Resolve the fixture at creation
// while keeping the strict identity check before recursive cleanup.
const source=path.resolve(__dirname,'..'),root=fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(),'oc-maintenance-fixture-'))),app=path.join(root,'OpenCode With Space'),home=path.join(root,'home'),runtime=path.join(root,'runtime'),maintenance=path.join(root,'maintenance'),backups=path.join(maintenance,'backups');
function ps(script,args=[]){const childEnv={...process.env};delete childEnv.PSModulePath;const r=cp.spawnSync('powershell.exe',['-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-File',script,...args],{encoding:'utf8',windowsHide:true,timeout:120000,env:childEnv});if(r.error||r.status!==0)throw new Error((r.stderr||r.stdout||r.error?.message).slice(-3500));return JSON.parse(r.stdout.replace(/^\uFEFF/,'').trim());}
const linkTool=path.join(root,'links.ps1');
try {
 for(const folder of [app,path.join(app,'resources'),home,runtime,maintenance,path.join(root,'Desktop')])fs.mkdirSync(folder,{recursive:true});
 fs.writeFileSync(path.join(app,'OpenCode.exe'),'fixture only');fs.writeFileSync(path.join(root,'python.exe'),'fixture interpreter, not executed');fs.writeFileSync(path.join(root,'pythonw.exe'),'fixture interpreter, not executed');
 const patched=p.patchAsar(makeAsar(baseFiles(),'1.18.34'),{platform:'windows',bridgeSource:fs.readFileSync(path.join(source,'shared/desktop-bridge.cjs'),'utf8'),micSource:fs.readFileSync(path.join(source,'shared/oc-mic.js'),'utf8')});fs.writeFileSync(path.join(app,'resources/app.asar'),patched.buffer);
 fs.writeFileSync(path.join(maintenance,'README.md'),'preexisting user helper documentation\n');
 fs.writeFileSync(linkTool,`param([string]$Root,[string]$App,[string]$Mode,[string]$Name='OpenCode.lnk')
$ErrorActionPreference='Stop'
$Shell=New-Object -ComObject WScript.Shell
$Target=Join-Path $App 'OpenCode.exe'
$LinkPath=Join-Path (Join-Path $Root 'Desktop') $Name
$Link=$Shell.CreateShortcut($LinkPath)
if($Mode -ne 'Read'){$Link.TargetPath=$Target;$Link.Arguments='--project "D:\\Fixture Space"';$Link.IconLocation=$Target+',0';$Link.Description=if($Mode -eq 'Replace'){'updated official link'}else{'original official link'};$Link.WorkingDirectory=$App;$Link.Hotkey='Ctrl+Alt+O';$Link.WindowStyle=3;$Link.Save()}
[ordered]@{path=$LinkPath;target=$Link.TargetPath;arguments=$Link.Arguments;icon=$Link.IconLocation;description=$Link.Description;workingDirectory=$Link.WorkingDirectory;hotkey=$Link.Hotkey;windowStyle=$Link.WindowStyle}|ConvertTo-Json
[void][Runtime.InteropServices.Marshal]::ReleaseComObject($Link)
[void][Runtime.InteropServices.Marshal]::ReleaseComObject($Shell)
`);
 const original=ps(linkTool,['-Root',root,'-App',app,'-Mode','Create']),initialBytes=fs.readFileSync(original.path);
 const installed=ps(path.join(source,'windows/install-maintenance.ps1'),['-PackageRoot',source,'-AppPath',app,'-VoiceHome',home,'-RuntimePath',runtime,'-BackupRoot',backups,'-MaintenanceRoot',maintenance,'-NodePath',process.execPath,'-PythonPath',path.join(root,'python.exe'),'-FixtureRoot',root]);
 assert.equal(installed.state,'applied');const active=path.join(maintenance,'active.json'),receipt=JSON.parse(fs.readFileSync(path.join(maintenance,'shortcut-receipt.json'),'utf8').replace(/^\uFEFF/,''));const maintained=ps(linkTool,['-Root',root,'-App',app,'-Mode','Read']);assert.match(maintained.target,/pythonw\.exe$/i);assert.ok(maintained.arguments.endsWith(original.arguments));assert.equal(maintained.description,original.description);assert.equal(maintained.hotkey,original.hotkey);assert.equal(maintained.windowStyle,original.windowStyle);assert.deepEqual(fs.readFileSync(receipt.entries[0].backupPath),initialBytes);
 const beforeRebind=fs.readFileSync(original.path);ps(path.join(installed.packageRoot,'windows/maintenance-shortcuts.ps1'),['-Mode','Rebind','-ConfigPath',active,'-FixtureRoot',root]);assert.deepEqual(fs.readFileSync(original.path),beforeRebind);
 ps(linkTool,['-Root',root,'-App',app,'-Mode','Replace']);const updatedOfficial=fs.readFileSync(original.path);ps(path.join(installed.packageRoot,'windows/maintenance-shortcuts.ps1'),['-Mode','Rebind','-ConfigPath',active,'-FixtureRoot',root]);const rebound=ps(linkTool,['-Root',root,'-App',app,'-Mode','Read']);assert.match(rebound.target,/pythonw\.exe$/i);assert.equal(rebound.description,'updated official link');
 const beforeDry=fs.readFileSync(original.path);const dry=ps(path.join(installed.packageRoot,'windows/restore-maintenance.ps1'),['-Transaction',installed.transaction,'-FixtureRoot',root,'-DryRun']);assert.equal(dry.state,'dry-run');assert.deepEqual(fs.readFileSync(original.path),beforeDry);
 const manifestPath=path.join(installed.transaction,'maintenance-transaction.json'),manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8').replace(/^\uFEFF/,'')),readmeBackup=manifest.before.find(entry=>entry.name==='README.md');assert.ok(readmeBackup?.backupPath);
 const savedReadme=fs.readFileSync(readmeBackup.backupPath),beforeRestoreActive=fs.readFileSync(active);fs.writeFileSync(readmeBackup.backupPath,'injected corrupt backup');
 assert.throws(()=>ps(path.join(installed.packageRoot,'windows/restore-maintenance.ps1'),['-Transaction',installed.transaction,'-FixtureRoot',root]),/maintenance backup hash mismatch/);assert.deepEqual(fs.readFileSync(original.path),beforeDry);assert.deepEqual(fs.readFileSync(active),beforeRestoreActive);assert.equal(JSON.parse(fs.readFileSync(manifestPath,'utf8').replace(/^\uFEFF/,'')).state,'restore-failed');fs.writeFileSync(readmeBackup.backupPath,savedReadme);
 const restored=ps(path.join(source,'windows/restore-maintenance.ps1'),['-Transaction',installed.transaction,'-FixtureRoot',root]);assert.equal(restored.state,'restored');assert.deepEqual(fs.readFileSync(original.path),updatedOfficial);assert.equal(fs.readFileSync(path.join(maintenance,'README.md'),'utf8'),'preexisting user helper documentation\n');assert.equal(fs.existsSync(active),false);
 const faultRoot=path.join(root,'failure'),faultApp=path.join(faultRoot,'app'),faultMaintenance=path.join(faultRoot,'maintenance');
 for(const directory of [faultApp,faultMaintenance,path.join(faultRoot,'Desktop')])fs.mkdirSync(directory,{recursive:true});
 fs.writeFileSync(path.join(faultApp,'OpenCode.exe'),'fixture app');const faultLauncher=path.join(faultMaintenance,'Launch-Voice.pyw');fs.writeFileSync(faultLauncher,'fixture launcher, never executed');
 const faultActive=path.join(faultMaintenance,'active.json'),faultReceipt=path.join(faultMaintenance,'shortcut-receipt.json');fs.writeFileSync(faultActive,JSON.stringify({schema:1,featureVersion:'0.2.0',app:faultApp,maintenanceRoot:faultMaintenance,shortcutReceipt:faultReceipt,launcherPath:faultLauncher,pythonw:path.join(root,'pythonw.exe')}));
 const first=ps(linkTool,['-Root',faultRoot,'-App',faultApp,'-Mode','Create','-Name','A.lnk']),second=ps(linkTool,['-Root',faultRoot,'-App',faultApp,'-Mode','Create','-Name','B.lnk']);const firstBytes=fs.readFileSync(first.path),secondBytes=fs.readFileSync(second.path);
 const injected=path.join(faultRoot,'shortcuts-failure.ps1');const needle='    $link.Save()';const injection='    if ([IO.Path]::GetFileName($Path) -eq "B.lnk") { throw "fixture second-save failure" }\n    $link.Save()\n    if ([IO.Path]::GetFileName($Path) -eq "A.lnk") { [IO.File]::WriteAllText((Join-Path (Split-Path -Parent $Path) "first-save-observed.txt"), "first shortcut was saved") }';const originalScript=fs.readFileSync(path.join(source,'windows/maintenance-shortcuts.ps1'),'utf8');assert.ok(originalScript.includes(needle));fs.writeFileSync(injected,originalScript.replace(needle,injection));
 assert.throws(()=>ps(injected,['-Mode','Install','-ConfigPath',faultActive,'-FixtureRoot',faultRoot]),/fixture second-save failure/);assert.ok(fs.existsSync(path.join(faultRoot,'Desktop/first-save-observed.txt')),'the first shortcut must actually have been changed before the injected failure');assert.deepEqual(fs.readFileSync(first.path),firstBytes);assert.deepEqual(fs.readFileSync(second.path),secondBytes);assert.equal(fs.existsSync(faultReceipt),false);
 const report={status:'PASS',platform:'Windows PowerShell 5.1, real isolated WSH shortcuts',checks:['install only in fenced fixture','byte-exact original shortcut backup','paths and arguments containing spaces','native icon, description, working directory, hotkey and window style','repeated rebind is byte-idempotent','NSIS recreated shortcut is rebound','restore remains valid after rebind','restore dry run has no link writes','restore latest official shortcut bytes','restore prior maintenance files','first shortcut actually changed before second-save failure','partial install restores both shortcuts and absent receipt'],actualUserShortcutsTouched:false};fs.mkdirSync(path.join(source,'test-results'),{recursive:true});fs.writeFileSync(path.join(source,'test-results/windows-maintenance-simulation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(error){console.error(error);process.exitCode=1;}finally{const actual=fs.realpathSync.native(root);assert.equal(actual.toLowerCase(),path.resolve(root).toLowerCase());assert.ok(path.basename(actual).startsWith('oc-maintenance-fixture-'));fs.rmSync(actual,{recursive:true,force:true});}
